#!/usr/bin/env python3
"""Create a local AutoRelay .env file without exposing generated secrets."""

from __future__ import annotations

import base64
import os
import secrets
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPOSITORY_ROOT / ".env"


def _fernet_key() -> str:
    """Return a URL-safe base64 encoding of exactly 32 random bytes."""

    return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def _render_environment(postgres_password: str, fernet_key: str) -> str:
    return f"""# Generated by scripts/bootstrap_env.py for local development.
# Keep this file private and do not commit it.
APP_ENV=development
POSTGRES_DB=autorelay
POSTGRES_USER=autorelay
POSTGRES_PASSWORD={postgres_password}
DATABASE_URL=postgresql+asyncpg://autorelay:{postgres_password}@localhost:5432/autorelay
FERNET_KEY={fernet_key}
SESSION_COOKIE_SECURE=false
SESSION_TTL_HOURS=168
CORS_ORIGINS=http://localhost:5173,http://localhost:8080
PUBLIC_BASE_URL=http://localhost:8080
ALLOW_PRIVATE_ACTION_TARGETS=false
WEBHOOK_MAX_PAYLOAD_BYTES=65536
ACTION_TIMEOUT_SECONDS=10
WORKER_POLL_INTERVAL_SECONDS=1
WORKER_CONCURRENCY=4
WORKER_MAX_ATTEMPTS=3
WORKER_STALE_AFTER_SECONDS=300
WORKER_RETRY_BASE_SECONDS=2
WORKER_RETRY_MAX_SECONDS=60
LOG_LEVEL=INFO
"""


def main() -> int:
    if ENV_PATH.exists():
        print(f"Preserved existing environment file: {ENV_PATH}")
        print("Next step: docker compose up --build")
        return 0

    postgres_password = secrets.token_urlsafe(32)
    contents = _render_environment(postgres_password, _fernet_key())

    try:
        descriptor = os.open(ENV_PATH, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        print(f"Preserved existing environment file: {ENV_PATH}")
        return 0

    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as env_file:
        env_file.write(contents)

    try:
        ENV_PATH.chmod(0o600)
    except OSError:
        # Some platforms do not implement POSIX permission bits. Exclusive
        # creation still prevents this script from replacing an existing file.
        pass

    print(f"Created private development environment file: {ENV_PATH}")
    print("Generated values were intentionally not printed.")
    print("Next step: docker compose up --build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
